---
name: Build Nix Flake

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: git-sidequest
          authToken: "${{ secrets.CACHIX_TOKEN }}"
          extraPullNames: nix-community,devenv,crane
      - run: nix flake check

  build:
    name: Build
    strategy:
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm", "macos-15-intel", "macos-15"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: git-sidequest
          authToken: "${{ secrets.CACHIX_TOKEN }}"
          extraPullNames: nix-community,devenv,crane
      - run: nix build .#
